version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    links:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_PASSWORD=123
    volumes:
      - portfolio_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  portfolio_db: